yelp_consumer_key: "5OZglI0D3RAccVHI5mHIGw"
yelp_consumer_secret: "j4BGnubGXYsNFe4grNnkc2wQmsQ"
yelp_token: "WCO8R6AQuVHzDiruJsLJKDya1QYKUnYv"
yelp_token_secret: "MlNzEwYB1RUngsYkK0evFRXFEcI"
instagram_client_id: "0b4f61fa696f4dd6b7764c40cfadf995"
instagram_client_secret: "f3a8829a320e4b6b8c8f454c18e21e42"